name = "GenomicFeatures"
uuid = "99b347e8-cb6a-11e8-1597-6bac6e11ce47"
authors = ["Kenta Sato <bicycle1885@gmail.com>", "Ben J. Ward <benjward@protonmail.com>", "Ciarán O’Mara <CiaranOMara@utas.edu.au>"]
version = "2.0.0"

[deps]
BioGenerics = "47718e42-2ac5-11e9-14af-e5595289c2ea"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
IntervalTrees = "524e6230-43b7-53ae-be76-1e9e4d08d11b"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test", "Distributions"]
