name = "GenomicFeatures"
uuid = "899a7d2d-5c61-547b-bef9-6698a8d05446"
authors = ["Kenta Sato <bicycle1885@gmail.com>", "Ben J. Ward <benjward@protonmail.com>", "Ciarán O’Mara <CiaranOMara@utas.edu.au>"]
version = "1.0.4"

[deps]
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
BGZFStreams = "28d598bf-9b8f-59f1-b38c-5a06b4a0f5e6"
BioCore = "37cfa864-2cd6-5c12-ad9e-b6597d696c81"
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
BufferedStreams = "e1450e63-4bb3-523b-b2a4-4ffa8c0fd77d"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
IntervalTrees = "524e6230-43b7-53ae-be76-1e9e4d08d11b"
Libz = "2ec943e9-cfe8-584d-b93d-64dcb6d567b7"
URIParser = "30578b45-9adc-5946-b283-645ec420af67"

[compat]
Automa = "0.7, 0.8"
BGZFStreams = "0.3"
BioCore = "2.0.2"
BioSequences = "1.0, 2.0"
BufferedStreams = "1.0.0"
ColorTypes = "0.7.4, 0.8, 0.9"
DataStructures = "0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17"
FixedPointNumbers = "0.5.2, 0.6, 0.7"
IntervalTrees = "1.0"
Libz = "1.0"
URIParser = "0.4"
julia = "0.7, 1"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[targets]
test = ["Random", "Test", "Distributions", "YAML"]
